version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_CONN: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
